"""empty message

Revision ID: 20ee77b531e0
Revises: a3c1708d714d
Create Date: 2022-04-11 12:51:33.959807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ee77b531e0'
down_revision = 'a3c1708d714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), nullable=True),
    sa.Column('trustFunds', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fund',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fundName', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fundDiscrib', sa.TEXT(), nullable=True),
    sa.Column('fundLink', sa.VARCHAR(length=500), nullable=True),
    sa.Column('fundImageLink', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fundName')
    )
    # ### end Alembic commands ###
